Repository Kernel360/KFE3-e2e-WONDERFUL, pull requests merged in 2025-07, with the labels that each got.

#198 Chore/vercel db #184
  .github/workflows/pr-preview-cleanup.yml
  .github/workflows/pr-preview-deploy.yml
  .github/workflows/sync-deploy.yml
  apps/web/app/api/auctions/[id]/route.ts
  apps/web/src/components/add-auction/add-auction-form.tsx
  apps/web/src/components/add-auction/add-auction-thumbnail.tsx
  apps/web/src/components/add-auction/category-select.tsx
  apps/web/src/components/auction-detail/bid-form.tsx
  apps/web/src/hooks/queries/category/useCategories.ts
  apps/web/src/lib/zustand/store/sort-store.ts
  apps/web/src/pages/AddAcutionPage.tsx
  apps/web/src/pages/AuctionPage.tsx
  apps/web/src/pages/ChatPage.tsx
  apps/web/src/pages/HomePage.tsx
  apps/web/src/pages/ProfilePage.tsx
  apps/web/src/pages/SearchPage.tsx
  apps/web/src/pages/SigninPage.tsx
  apps/web/src/pages/SignupPage.tsx
  apps/web/src/pages/profile/TradePage.tsx
  packages/db/prisma/schema.prisma
Labels: 🌏 Deploy

#206 [Fix] Vercel 프리즈마 참조 못하는 버그
  .github/workflows/pr-preview-deploy.yml
  apps/web/next.config.ts
  apps/web/package.json
  packages/db/package.json
  packages/db/prisma/schema.prisma
  pnpm-lock.yaml
  turbo.json
  vercel.json
Labels: 🌏 Deploy

#208 [fix] 경매상태에 따른 뱃지가 제대로 보이지 않는 이슈 해결
  apps/web/app/api/auctions/route.ts
  apps/web/src/components/auction-detail/item-images.tsx
  apps/web/src/components/common/auction-item-List.tsx
  apps/web/src/components/common/auction-item-card.tsx
  apps/web/src/hooks/common/useCountdown.ts
  apps/web/src/hooks/queries/auction/keys.ts
  apps/web/src/hooks/queries/auction/useAuctions.ts
  apps/web/src/lib/api/auction.ts
  packages/db/prisma/migrations/20250702085418_add_status_default/migration.sql
  packages/db/prisma/migrations/20250702093120_make_location_optional/migration.sql
  packages/db/prisma/schema.prisma
Labels: 🐛 Bug, 📬 API, 📝 Style

#213 [fix] bidform current price #211
  apps/web/src/components/auction-detail/banner-direct.tsx
  apps/web/src/components/auction-detail/bid-form.tsx
  apps/web/src/components/auction-detail/item-information.tsx
  apps/web/src/pages/AuctionPage.tsx
  apps/web/src/pages/HomePage.tsx
Labels: ✨ Feature, 🐛 Bug, 📝 Style

#227 [refactor] 컴포넌트 폴더 정리
  apps/web/app/layout.tsx
  apps/web/src/app/index.ts
  apps/web/src/components/auction-create/form-create.tsx
  apps/web/src/components/auction-detail/bid-input.tsx
  apps/web/src/components/auction-detail/button-detail-more.tsx
  apps/web/src/components/auction-detail/countdown.tsx
  apps/web/src/components/auction-detail/item-information.tsx
  apps/web/src/components/auction-edit/form-edit.tsx
  apps/web/src/components/auction-test.tsx
  apps/web/src/components/auth/auth-form.tsx
  apps/web/src/components/chat/chat-list-item.tsx
  apps/web/src/components/common/attach-images/attach-images-input.tsx
  apps/web/src/components/common/attach-images/attach-images-thumbnail.tsx
  apps/web/src/components/common/attach-images/attach-images.tsx
  apps/web/src/components/common/auction-card/badge-bid-status.tsx
  apps/web/src/components/common/auction-card/card.tsx
  apps/web/src/components/common/auction-card/list.tsx
  apps/web/src/components/common/button/create-auction.tsx
  apps/web/src/components/common/button/more.tsx
  apps/web/src/components/common/date-picker.tsx
  apps/web/src/components/common/input/basic.tsx
  apps/web/src/components/common/input/icon.tsx
  apps/web/src/components/common/logout-button.tsx
  apps/web/src/components/common/messages/error-msg.tsx
  apps/web/src/components/common/messages/notice.tsx
  apps/web/src/components/common/profile/card.tsx
  apps/web/src/components/common/profile/image.tsx
  apps/web/src/components/common/profile/menu-list.tsx
  apps/web/src/components/common/select/basic.tsx
  apps/web/src/components/common/select/category.tsx
  apps/web/src/components/common/select/min-unit.tsx
  apps/web/src/components/common/tab/basic.tsx
  apps/web/src/components/common/tab/list-filter.tsx
  apps/web/src/components/common/time-picker.tsx
  apps/web/src/components/layout/home-selectbox.tsx
  apps/web/src/components/test/storage-test.tsx
  apps/web/src/components/ui/tab-filter.tsx
  apps/web/src/components/ui/thumbnail.tsx
  apps/web/src/providers/query-provider.tsx
  apps/web/src/views/AuctionPage.tsx
  apps/web/src/views/CreateAcutionPage.tsx
  apps/web/src/views/EditAuctionPage.tsx
  apps/web/src/views/HomePage.tsx
  apps/web/src/views/ProfilePage.tsx
  apps/web/src/views/profile/TradePage.tsx
Labels: 🔨 Refactor, 📁 Rename

#245 [Feat] 회원가입, 소셜로그인(구글)
  .github/workflows/pr-preview-deploy.yml
  apps/web/app/auth/callback/route.ts
  apps/web/app/auth/confirm/route.ts
  apps/web/app/auth/signin/page.tsx
  apps/web/app/auth/signup/page.tsx
  apps/web/public/icon/kakao.svg
  apps/web/src/components/auth/auth-form.tsx
  apps/web/src/components/auth/error-message.tsx
  apps/web/src/components/auth/password-toggle.tsx
  apps/web/src/components/auth/signin-form.tsx
  apps/web/src/components/auth/signin/google-login-buttons.tsx
  apps/web/src/components/auth/signin/signin-fields.tsx
  apps/web/src/components/auth/signin/signin-form.tsx
  apps/web/src/components/auth/signin/signin-view.tsx
  apps/web/src/components/auth/signup-form.tsx
  apps/web/src/components/auth/signup/signup-fields.tsx
  apps/web/src/components/auth/signup/signup-form.tsx
  apps/web/src/components/auth/signup/signup-view.tsx
  apps/web/src/components/auth/submit-button.tsx
  apps/web/src/lib/actions/auth.action.ts
  apps/web/src/lib/supabase/middleware.ts
  apps/web/src/lib/types/auth.ts
  apps/web/src/lib/utils/auth.ts
  apps/web/src/views/SigninPage.tsx
  apps/web/src/views/SignupPage.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 🔨 Refactor, 📁 Rename

#256 [feat] gachagame UI 구현 및 서버컴포넌트로 변경
  apps/web/app/gacha/page.tsx
  apps/web/package.json
  apps/web/src/components/game/ball.tsx
  apps/web/src/components/game/confetti.tsx
  apps/web/src/components/game/gacha-client.tsx
  apps/web/src/components/game/hint.tsx
  apps/web/src/hooks/common/useGachaGame.ts
  apps/web/src/lib/constants/game.ts
  apps/web/src/lib/types/game.ts
  apps/web/src/lib/types/index.ts
  packages/eslint-config/next.js
  pnpm-lock.yaml
Labels: 💄 UI, 📝 Style

#257 [chore] components/common/index.ts 생성 및 정리
  apps/web/src/components/common/attach-images/attach-images-thumbnail.tsx
  apps/web/src/components/common/attach-images/attach-images.tsx
  apps/web/src/components/common/auction-card/card.tsx
  apps/web/src/components/common/auction-card/index.ts
  apps/web/src/components/common/auction-card/list.tsx
  apps/web/src/components/common/button/index.ts
  apps/web/src/components/common/index.ts
  apps/web/src/components/common/profile/card.tsx
  apps/web/src/components/common/profile/index.ts
  apps/web/src/components/common/select/basic.tsx
  apps/web/src/components/common/select/category.tsx
  apps/web/src/components/common/select/min-unit.tsx
  apps/web/src/components/common/tab/index.ts
  apps/web/src/views/AuctionPage.tsx
  apps/web/src/views/CreateAcutionPage.tsx
  apps/web/src/views/HomePage.tsx
  apps/web/src/views/ProfilePage.tsx
  apps/web/src/views/profile/TradePage.tsx
  apps/web/src/views/profile/WishlistPage.tsx
Labels: ⚙ Chores, 📝 Style

#259 [Feat] 프로필 수정 페이지 #249
  apps/web/app/profile/edit/page.tsx
  apps/web/src/components/common/profile/card.tsx
  apps/web/src/components/common/profile/edit/form-edit.tsx
  apps/web/src/components/common/profile/edit/nickname.tsx
  apps/web/src/components/common/profile/edit/profile-image-uploader.tsx
  apps/web/src/components/common/profile/image.tsx
  apps/web/src/components/layout/header/profile.tsx
  apps/web/src/components/ui/avatar.tsx
  apps/web/src/views/ProfilePage.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#261 [chore] motion 라이브러리 설치
  apps/web/package.json
Labels: ⚙ Chores

#282 [refactor] bid table 수정 및 AutoAnimation 적용
  apps/web/app/auction/[id]/layout.tsx
  apps/web/app/auction/[id]/page.tsx
  apps/web/app/auction/layout.tsx
  apps/web/package.json
  apps/web/src/components/auction-create/form-create.tsx
  apps/web/src/components/auction-detail/bid-table.tsx
  apps/web/src/components/auction-detail/bid-table/bid-table.tsx
  apps/web/src/components/auction-detail/bid-table/bidder-avatar.tsx
  apps/web/src/components/auction-detail/bid-table/head.tsx
  apps/web/src/components/auction-detail/bid-table/row.tsx
  apps/web/src/components/auction-detail/container.tsx
  apps/web/src/components/auction-detail/index.tsx
  apps/web/src/components/auction-detail/item-description.tsx
  apps/web/src/components/auction-detail/item-summary.tsx
  apps/web/src/components/common/index.ts
  apps/web/src/components/common/select/basic.tsx
  apps/web/src/components/common/select/category.tsx
  apps/web/src/components/common/select/min-unit.tsx
  apps/web/src/lib/constants/bid-list.ts
  apps/web/src/lib/types/bid.ts
  packages/tailwind-config/shared-styles.css
  pnpm-lock.yaml
Labels: 🔨 Refactor

#293 [Refactor] signup 커스텀훅
  apps/web/app/auth/signup/page.tsx
  apps/web/src/components/auth/bottom-modal.tsx
  apps/web/src/components/auth/reset-password/reset-password-form.tsx
  apps/web/src/components/auth/signup/index.ts
  apps/web/src/components/auth/signup/kakao-map.tsx
  apps/web/src/components/auth/signup/location-display.tsx
  apps/web/src/components/auth/signup/location-setup.tsx
  apps/web/src/components/auth/signup/signup-done.tsx
  apps/web/src/components/auth/signup/signup-flow.tsx
  apps/web/src/components/auth/signup/signup-form.tsx
  apps/web/src/components/auth/signup/signup-success.tsx
  apps/web/src/components/auth/signup/signup-view.tsx
  apps/web/src/components/chat/received-message.tsx
  apps/web/src/components/chat/sent-message.tsx
  apps/web/src/components/common/profile/index.ts
  apps/web/src/hooks/auth/index.ts
  apps/web/src/hooks/auth/useAuthCommon.ts
  apps/web/src/hooks/auth/useResetPasswordFlow.ts
  apps/web/src/hooks/auth/useResetPasswordForm.ts
  apps/web/src/hooks/auth/useSignupFlow.ts
  apps/web/src/hooks/auth/useSignupForm.ts
  pnpm-lock.yaml
Labels: 🔨 Refactor

#297 [refactor] profile build 에러 수정
  apps/web/app/chat/page.tsx
  apps/web/app/profile/user/page.tsx
  apps/web/src/components/auction/categories-filter.tsx
  apps/web/src/components/user/button-sign-out.tsx
  apps/web/src/components/user/my-profile.tsx
  apps/web/src/components/user/other-profile.tsx
Labels: 🔨 Refactor

#308 [fix] pnpm 버전 삭제
  .github/workflows/pr-preview-deploy.yml
Labels: 🐛 Bug

#305 [feat] 찜하기 api 생성 및 컴포넌트 적용
  apps/web/app/api/auctions/[id]/route.ts
  apps/web/app/api/favorites/[itemId]/route.ts
  apps/web/src/components/auction-detail/bid-form.tsx
  apps/web/src/components/auction-detail/button-favorite.tsx
  apps/web/src/components/auction-detail/container.tsx
  apps/web/src/components/common/profile/index.ts
  apps/web/src/components/user/my-profile.tsx
  apps/web/src/components/user/other-profile.tsx
  apps/web/src/hooks/mutations/favorites/index.ts
  apps/web/src/hooks/queries/auction/index.ts
  apps/web/src/hooks/queries/auction/keys.ts
  apps/web/src/lib/api/favorites.ts
  apps/web/src/lib/types/auction-prisma.ts
Labels: ✨ Feature, 📬 API

#330 [feat] 타임존 동기화 로직 추가
  apps/docs/stories/Bage.stories.tsx
  apps/docs/stories/Button.stories.tsx
  apps/web/src/components/auction-detail/container.tsx
  apps/web/src/components/auction-detail/item-summary.tsx
  apps/web/src/lib/utils/date.ts
Labels: ✨ Feature

#343 [feature] 채팅 목록 호출 api 작성 및 연결
  apps/web/app/api/chat/route.ts
  apps/web/app/chat/page.tsx
  apps/web/src/components/chat/button-chat-more.tsx
  apps/web/src/components/chat/chat-list-card.tsx
  apps/web/src/components/chat/chat-list-item.tsx
  apps/web/src/components/chat/index.ts
  apps/web/src/components/common/profile/edit/form-edit.tsx
  apps/web/src/hooks/chat/useChatRoom.ts
  apps/web/src/lib/api/chat.ts
  apps/web/src/lib/types/chat.ts
Labels: ✨ Feature, 🔨 Refactor

#350 [fix] 타임존 롤백
  apps/web/src/components/auction-detail/item-summary.tsx
Labels: 🐛 Bug

#355 [feat] 경매 수정 기능 구현
  apps/web/app/auction/[id]/edit/page.tsx
  apps/web/package.json
  apps/web/src/components/auction-create/form-create.tsx
  apps/web/src/components/auction-detail/container.tsx
  apps/web/src/components/auction-edit/form-edit.tsx
  apps/web/src/components/common/attach-images/attach-images.tsx
  apps/web/src/components/common/auction-card/list.tsx
  apps/web/src/components/common/error-boundary-wrapper.tsx
  apps/web/src/components/common/select-box/basic.tsx
  apps/web/src/components/common/select-box/category.tsx
  apps/web/src/components/common/select-box/min-unit.tsx
  apps/web/src/components/layout/header/auction.tsx
  apps/web/src/components/ui/alert-dialog.tsx
  apps/web/src/hooks/auction/useCreateAuction.tsx
  apps/web/src/hooks/auction/useEditAuction.tsx
  apps/web/src/hooks/mutations/bids/index.ts
  apps/web/src/lib/actions/auction.ts
  apps/web/src/lib/types/auction.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#362 [Feat]검색 기능
  apps/web/app/api/search/route.ts
  apps/web/app/profile/page.tsx
  apps/web/app/search/page.tsx
  apps/web/src/components/common/auction-card/list.tsx
  apps/web/src/components/layout/header/search.tsx
  apps/web/src/components/search/input-search.tsx
  apps/web/src/components/search/search-log.tsx
  apps/web/src/components/search/search-result.tsx
  apps/web/src/hooks/common/useSearchHistory.ts
  apps/web/src/hooks/queries/index.ts
  apps/web/src/hooks/queries/search/index.ts
  apps/web/src/hooks/queries/search/keys.ts
  apps/web/src/lib/api/search.ts
  apps/web/src/lib/constants/search.ts
  apps/web/src/lib/types/search.ts
  apps/web/src/lib/utils/auction.ts
  apps/web/src/lib/zustand/store/filter-store.ts
Labels: ✨ Feature, 📬 API

#378 [fix] chat api 호출 에러 해결
  apps/web/app/api/chat/route.ts
  apps/web/src/lib/types/chat.ts
Labels: 🐛 Bug

#382 [fix] chat header 상대방 닉네임 추가
  apps/web/src/components/chat/chat-list-card.tsx
  apps/web/src/components/common/button/back.tsx
  apps/web/src/components/layout/header/chat.tsx
Labels: ✨ Feature

#384 [feat] 경매상세페이지 UI 개선
  apps/web/app/api/bids/route.ts
  apps/web/app/api/search/route.ts
  apps/web/src/components/auction-create/form-create.tsx
  apps/web/src/components/auction-detail/bid-form/form.tsx
  apps/web/src/components/auction-detail/bid-form/input.tsx
  apps/web/src/components/auction-detail/container.tsx
  apps/web/src/components/auction-edit/form-edit.tsx
  apps/web/src/components/common/input/icon.tsx
  apps/web/src/components/common/toast.tsx
  apps/web/src/hooks/auction/useEditAuction.tsx
  apps/web/src/lib/utils/price.ts
  packages/db/prisma/schema.prisma
Labels: ✨ Feature

#393 [fix] Sentry 405 에러 해결을 위한 터널링 설정 추가
  apps/web/sentry.client.config.ts
  apps/web/sentry.server.config.ts
Labels: 🐛 Bug

#403 [feat] 경매상세페이지 헤더 섀도우 추가
  apps/web/src/components/common/button/more.tsx
  apps/web/src/components/layout/header/auction.tsx
  apps/web/src/components/layout/header/wrapper.tsx
  packages/tailwind-config/shared-styles.css
Labels: ✨ Feature

#407 [feat] 경매목록카드와 상단 카테고리 스켈레톤ui 구현
  apps/web/src/components/auction/auction-card-skeleton.tsx
  apps/web/src/components/auction/categories-filter.tsx
  apps/web/src/components/common/auction-card/list.tsx
Labels: ✨ Feature

#409 [fix] 모바일에서 경매등록 숫자 입력 호환처리
  apps/web/src/components/auction-create/form-create.tsx
  apps/web/src/components/common/select-box/basic.tsx
  apps/web/src/hooks/common/useNumberInput.ts
Labels: 🐛 Bug

#412 [feat] 계좌 api 등록
  apps/web/app/account/create/page.tsx
  apps/web/app/account/edit/[id]/page.tsx
  apps/web/src/components/common/toast.tsx
  apps/web/src/components/personal-info/account/form.tsx
  apps/web/src/hooks/mutations/accounts/index.ts
  apps/web/src/hooks/queries/accounts/index.ts
  apps/web/src/lib/actions/account.ts
  apps/web/src/lib/types/account.ts
Labels: ✨ Feature
