Repository Kernel360/KFE3-e2e-WONDERFUL, pull requests merged in 2025-06, with the labels that each got.

#5 [Chore] eslint, prettier 설정
  .prettierignore
  .prettierrc
  .prettierrc.js
  .vscode/settings.json
  apps/docs/app/components/common/Card.tsx
  apps/docs/app/components/common/Category.tsx
  apps/docs/app/components/common/input/InputCheckBox.tsx
  apps/docs/app/components/common/input/InputText.tsx
  apps/docs/app/components/common/input/InputToggle.tsx
  apps/docs/app/layout.tsx
  apps/docs/app/layout/NavBar.tsx
  apps/docs/app/layout/header/Header.tsx
  apps/web/app/layout.tsx
  package.json
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  packages/ui/eslint.config.mjs
  pnpm-lock.yaml
Labels: ⚙ Chores

#6 [chore] lefthook 설정
  .npmrc
  apps/docs/.storybook/main.ts
  apps/docs/app/page.tsx
  apps/docs/stories/Bage.stories.tsx
  apps/docs/stories/Button.stories.tsx
  apps/docs/tsconfig.json
  apps/docs/vitest.config.ts
  apps/web/app/page.tsx
  apps/web/tsconfig.json
  lefthook.yml
  package.json
  packages/ui/src/components/common/Avatar.tsx
  packages/ui/src/components/common/Badge.tsx
  packages/ui/src/components/common/Button.tsx
  packages/ui/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ⚙ Chores

#13 [chore] 나머지 frontend 초기 세팅
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/components.json
  apps/web/eslint.config.js
  apps/web/lib/utils.ts
  apps/web/next-env.d.ts
  apps/web/next.config.ts
  apps/web/package.json
  apps/web/src/app/index.ts
  apps/web/src/entities/index.ts
  apps/web/src/features/index.ts
  apps/web/src/pages/home/index.ts
  apps/web/src/pages/home/ui/HomePage.tsx
  apps/web/src/shared/api/index.ts
  apps/web/src/shared/api/test.ts
  apps/web/src/shared/config/index.ts
  apps/web/src/shared/constants/index.ts
  apps/web/src/shared/index.ts
  apps/web/src/shared/lib/hooks/index.ts
  apps/web/src/shared/lib/providers/query-provider.tsx
  apps/web/src/shared/lib/store/index.ts
  apps/web/src/shared/lib/utils/index.ts
  apps/web/src/shared/types/index.ts
  apps/web/src/shared/ui/components/index.ts
  apps/web/src/shared/ui/components/test-lucide.tsx
  apps/web/src/shared/ui/index.ts
  apps/web/src/widgets/index.ts
  apps/web/tsconfig.json
  lefthook.yml
  packages/eslint-config/next.js
  pnpm-lock.yaml
Labels: ⚙ Chores

#15 [chore] supabase, prisma 초기 설정
  .gitignore
  apps/web/package.json
  eslint.config.mjs
  packages/db/package.json
  packages/db/prisma/schema.prisma
  packages/db/src/client.ts
  packages/db/src/index.ts
  packages/db/tsconfig.json
  packages/eslint-config/next.js
  pnpm-lock.yaml
  turbo.json
Labels: ⚙ Chores

#32 [chore] 폰트 설정 및 팀 규칙 수정
  apps/web/app/layout.tsx
  apps/web/public/fonts/PretendardVariable.woff2
  packages/eslint-config/next.js
  packages/tailwind-config/shared-styles.css
Labels: ⚙ Chores

#40 [feat] layout 컴포넌트 생성
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/next-env.d.ts
  apps/web/src/components/layout/Header.tsx
  apps/web/src/components/layout/MainLayout.tsx
  apps/web/src/components/layout/Navigation.tsx
  apps/web/src/components/layout/index.ts
  apps/web/src/components/pages/HomePage.tsx
  apps/web/src/components/ui/navigation-menu.tsx
  apps/web/src/pages/HomePage.tsx
  apps/web/tsconfig.json
  packages/tailwind-config/shared-styles.css
Labels: ✨ Feature

#55 [feat] Header 컴포넌트 생성 및 레이아웃 적용
  apps/web/src/components/layout/Header.tsx
  apps/web/src/components/layout/MainLayout.tsx
Labels: ✨ Feature

#59 [fix] vercel 의존성 문제
  .github/workflows/sync-and-deploy.yml
  vercel.json
Labels: 🐛 Bug, 🌏 Deploy

#56 [feat] 네비게이션과 메인 페이지들 연결
  apps/web/app/chat/page.tsx
  apps/web/app/profile/page.tsx
  apps/web/app/search/page.tsx
  apps/web/src/components/layout/Navigation.tsx
  apps/web/src/constants/routes.ts
  apps/web/src/pages/ChatPage.tsx
  apps/web/src/pages/HomePage.tsx
  apps/web/src/pages/ProfilePage.tsx
  apps/web/src/pages/SearchPage.tsx
Labels: ✨ Feature

#67 Feat/button #24
  apps/web/package.json
  apps/web/src/components/ui/button.tsx
  apps/web/src/components/ui/float-button.tsx
  pnpm-lock.yaml
Labels: ⚙ Chores, ✨ Feature

#66 feat: profile image 제작
  apps/web/package.json
  apps/web/src/components/common/profile-image.tsx
  apps/web/src/components/ui/avatar.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#104 [feat] Thumbnail 컴포넌트 제작
  apps/web/src/components/common/thumbnail.tsx
Labels: ✨ Feature

#105 [chore] supabase realtime 설정 및 기능확인 용 테스트 페이지 추가
  .github/workflows/vercel-deploy.yml
  apps/web/src/components/chat/chat-room.tsx
  apps/web/src/components/chat/chat-test.tsx
  apps/web/src/components/ui/realtime-test/index.ts
  apps/web/src/components/ui/realtime-test/realtime-test.tsx
  apps/web/src/hooks/index.ts
  apps/web/src/hooks/queries/index.ts
  apps/web/src/hooks/queries/users/index.ts
  apps/web/src/hooks/queries/users/useUsers.ts
  apps/web/src/lib/supabase.ts
  apps/web/src/pages/HomePage.tsx
  apps/web/src/types/chat.ts
Labels: ⚙ Chores

#117 [feat] menu list 제작 #74
  apps/web/src/components/common/menu-list.tsx
Labels: ✨ Feature

#122 [feat] Logout Button 제작 #75
  apps/web/src/components/common/logout-button.tsx
Labels: 💄 UI

#124 [feat] AuctionItemList 컴포넌트 생성 및 HomePage 퍼블리싱
  apps/web/src/components/categories/categories.tsx
  apps/web/src/components/common/auction-item-List.tsx
  apps/web/src/components/common/auction-item-card.tsx
  apps/web/src/components/ui/tabs-categories.tsx
  apps/web/src/pages/HomePage.tsx
  apps/web/src/types/auction.ts
  packages/tailwind-config/shared-styles.css
Labels: ✨ Feature, 💄 UI

#134 [fix] import 오류 수정
  apps/web/src/components/layout/dynamic-header.tsx
  apps/web/src/pages/AuctionPage.tsx
  apps/web/src/pages/ProfilePage.tsx
Labels: 🐛 Bug, 📝 Style

#150 [chore] 폴더구조 수정 및 import 경로 수정
  apps/web/app/layout.tsx
  apps/web/src/components/auction-detail/bid-form.tsx
  apps/web/src/components/auction-detail/bid-input.tsx
  apps/web/src/components/auction-detail/item-information.tsx
  apps/web/src/components/auth/SigninForm.tsx
  apps/web/src/components/auth/SignupForm.tsx
  apps/web/src/components/auth/authForm.tsx
  apps/web/src/components/chat/chat-room.tsx
  apps/web/src/components/common/auction-item-List.tsx
  apps/web/src/components/common/auction-item-card.tsx
  apps/web/src/components/common/countdown.tsx
  apps/web/src/components/common/thumbnail.tsx
  apps/web/src/components/common/time-picker.tsx
  apps/web/src/components/layout/navigation.tsx
  apps/web/src/components/providers/query-provider.tsx
  apps/web/src/components/ui/avatar.tsx
  apps/web/src/components/ui/badge.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/components/ui/calendar.tsx
  apps/web/src/components/ui/carousel.tsx
  apps/web/src/components/ui/float-button.tsx
  apps/web/src/components/ui/input.tsx
  apps/web/src/components/ui/label.tsx
  apps/web/src/components/ui/navigation-menu.tsx
  apps/web/src/components/ui/popover.tsx
  apps/web/src/components/ui/realtime-test/realtime-test.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/components/ui/tab-basic.tsx
  apps/web/src/components/ui/table.tsx
  apps/web/src/components/ui/tabs-categories.tsx
  apps/web/src/components/ui/test-lucide.tsx
  apps/web/src/hooks/common/useCountdown.ts
  apps/web/src/hooks/queries/users/useUsers.ts
  apps/web/src/lib/api/client.ts
  apps/web/src/lib/api/index.ts
  apps/web/src/lib/api/test.ts
  apps/web/src/lib/api/users.ts
  apps/web/src/lib/cn.ts
  apps/web/src/lib/config/index.ts
  apps/web/src/lib/constants/index.ts
  apps/web/src/lib/constants/routes.ts
  apps/web/src/lib/supabase/supabase-client.ts
  apps/web/src/lib/supabase/supabase-middleware.ts
  apps/web/src/lib/supabase/supabase-server.ts
  apps/web/src/lib/types/auction.ts
  apps/web/src/lib/types/auth.ts
  apps/web/src/lib/types/chat.ts
  apps/web/src/lib/types/index.ts
  apps/web/src/lib/types/users.ts
  apps/web/src/lib/utils/auth.ts
  apps/web/src/lib/utils/date.ts
  apps/web/src/lib/utils/index.ts
  apps/web/src/lib/utils/price.ts
  apps/web/src/lib/zustand/store/index.ts
  apps/web/src/pages/SigninPage.tsx
  apps/web/src/pages/SignupPage.tsx
  apps/web/tsconfig.json
Labels: 📝 Style, 📁 Rename

#153 feat: 등록한 경매 내역 페이지 퍼플리싱 #142
  apps/web/app/profile/sales/page.tsx
  apps/web/src/components/categories/categories.tsx
  apps/web/src/lib/constants/tabs.ts
  apps/web/src/pages/HomePage.tsx
  apps/web/src/pages/profile/TradePage.tsx
Labels: ✨ Feature

#157 [feat] API 클라이언트(client.ts)
  apps/web/src/lib/api/client.ts
Labels: ✨ Feature

#165 [feat] 경매 목록 API 구현
  apps/web/app/api/auctions/route.ts
  apps/web/app/auction-list-test/page.tsx
  apps/web/src/components/auction-test.tsx
  apps/web/src/hooks/queries/auction/index.ts
  apps/web/src/hooks/queries/auction/keys.ts
  apps/web/src/hooks/queries/auction/useAuctions.ts
  apps/web/src/lib/api/auction.ts
  apps/web/src/lib/types/auction.ts
  packages/eslint-config/next.js
Labels: ✨ Feature, 📬 API

#172 [feat] checkbox 컴포넌트 생성
  apps/web/package.json
  apps/web/src/components/ui/checkbox.tsx
  apps/web/src/pages/HomePage.tsx
Labels: ✨ Feature

#168 [Feat] 경매 등록 페이지 라우트 생성
  apps/web/app/auction/addAuction/page.tsx
  apps/web/app/auction/addItem/page.tsx
  apps/web/components/pages/AddAuctionPage.tsx
Labels: ✨ Feature

#171 [Feat] location api #151
  apps/web/src/components/auth/auth-form.tsx
  apps/web/src/components/auth/bottom-modal.tsx
  apps/web/src/components/auth/kakao-map.tsx
  apps/web/src/components/auth/location-display.tsx
  apps/web/src/components/auth/location-setup.tsx
  apps/web/src/components/auth/signin-form.tsx
  apps/web/src/components/auth/signup-done.tsx
  apps/web/src/components/auth/signup-form.tsx
  apps/web/src/components/location/location-search-form.tsx
  apps/web/src/hooks/common/useGeolocation.ts
  apps/web/src/lib/api/kakao-geocoding.ts
  apps/web/src/pages/SigninPage.tsx
  apps/web/src/pages/SignupPage.tsx
Labels: ✨ Feature

#179 [feat] 경매 상세페이지 API Routes
  apps/web/app/api/auctions/[id]/route.ts
  apps/web/app/api/auctions/route.ts
  apps/web/public/avatar-female.svg
  apps/web/public/avatar-male.svg
  apps/web/public/no-image.png
  apps/web/src/components/auction-detail/button-favorite.tsx
  apps/web/src/components/auction-detail/item-images.tsx
  apps/web/src/components/auction-test.tsx
  apps/web/src/hooks/queries/auction/keys.ts
  apps/web/src/hooks/queries/auction/useAuctions.ts
  apps/web/src/lib/api/auction.ts
  apps/web/src/lib/types/auction.ts
  apps/web/src/lib/utils/images.ts
  apps/web/src/pages/ProfilePage.tsx
  packages/db/prisma/migrations/20250629114710_add_favorite_unique_constraint/migration.sql
  packages/db/prisma/migrations/20250629163437_change_url_to_urls_array/migration.sql
  packages/db/prisma/schema.prisma
  pnpm-lock.yaml
Labels: ✨ Feature, 📬 API

#191 [style] 이전 헤더로 롤백, params 비동기 처리
  apps/web/app/api/auctions/[id]/route.ts
  apps/web/app/api/auctions/route.ts
  apps/web/src/components/common/auction-item-List.tsx
  apps/web/src/components/layout/dynamic-header.tsx
  apps/web/src/components/layout/home-selectbox.tsx
  apps/web/src/lib/api/auction.ts
  apps/web/src/lib/api/client.ts
  apps/web/src/lib/types/index.ts
Labels: 📝 Style

#192 [feat] add auction form 컴포넌트 생성 및 퍼블리싱
  apps/web/app/auction/addAuction/page.tsx
  apps/web/app/auction/addItem/page.tsx
  apps/web/components/pages/AddAuctionPage.tsx
  apps/web/src/components/add-auction/add-auction-form.tsx
  apps/web/src/components/add-auction/attache-image-input.tsx
  apps/web/src/components/add-auction/category-select.tsx
  apps/web/src/components/add-auction/images-uploader.tsx
  apps/web/src/components/add-auction/min-unit-select.tsx
  apps/web/src/components/common/notice.tsx
  apps/web/src/components/ui/index.ts
  apps/web/src/components/ui/input.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/components/ui/textarea.tsx
  apps/web/src/hooks/auction/useDeletePreview.tsx
  apps/web/src/hooks/auction/useOnChangePreview.tsx
  apps/web/src/hooks/auction/usePostAuction.tsx
  apps/web/src/lib/constants/tabs.ts
  apps/web/src/lib/types/auction.ts
  apps/web/src/pages/AddAcutionPage.tsx
Labels: ✨ Feature
