Repository Kernel360/KFE3-e2e-WONDERFUL, pull requests merged in 2025-08, with the labels that each got.

#447 [fix] 전체 페이지 layout 수정 및 스타일 수정
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/app/profile/page.tsx
  apps/web/app/profile/purchases/page.tsx
  apps/web/app/profile/sales/page.tsx
  apps/web/app/profile/user/page.tsx
  apps/web/app/search/page.tsx
  apps/web/src/components/auction-create/form-create.tsx
  apps/web/src/components/auction-detail/bid-form/bottom.tsx
  apps/web/src/components/auction-detail/bid-form/button-direct-deal.tsx
  apps/web/src/components/auction-detail/bid-form/form.tsx
  apps/web/src/components/auction-detail/bid-form/input.tsx
  apps/web/src/components/auction-detail/bid-table/bid-table.tsx
  apps/web/src/components/auction-detail/container.tsx
  apps/web/src/components/auction-detail/item-images.tsx
  apps/web/src/components/auction/auction-list.tsx
  apps/web/src/components/auction/categories-filter.tsx
  apps/web/src/components/common/attach-images/attach-images-thumbnail.tsx
  apps/web/src/components/common/attach-images/attach-images.tsx
  apps/web/src/components/common/auction-card/card.tsx
  apps/web/src/components/common/auction-card/list.tsx
  apps/web/src/components/common/button/create-auction.tsx
  apps/web/src/components/common/profile/card.tsx
  apps/web/src/components/common/profile/menu-list.tsx
  apps/web/src/components/common/profile/shortcut-menu.tsx
  apps/web/src/components/common/tab/filter.tsx
  apps/web/src/components/layout/container.tsx
  apps/web/src/components/layout/header/auction.tsx
  apps/web/src/components/layout/header/profile.tsx
  apps/web/src/components/layout/header/search.tsx
  apps/web/src/components/layout/header/wrapper.tsx
  apps/web/src/components/layout/home-filter-select.tsx
  apps/web/src/components/layout/navigation.tsx
  apps/web/src/components/personal-info/purchases/purchases-list.tsx
  apps/web/src/components/personal-info/sales/sales-list.tsx
  apps/web/src/components/personal-info/wish/wishlist.tsx
  apps/web/src/components/search/input-search.tsx
  apps/web/src/components/search/search-result.tsx
  apps/web/src/components/ui/carousel.tsx
  apps/web/src/components/ui/popover.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/components/user/button-sign-out.tsx
  apps/web/src/lib/constants/profile.ts
  apps/web/src/lib/types/bid.ts
  apps/web/src/lib/types/filter.ts
  apps/web/src/lib/zustand/store/toast-store.ts
  apps/web/src/views/CreateAcutionPage.tsx
Labels: 🐛 Bug, 🔨 Refactor, 📝 Style

#449 [refactor] 카드 ui 수정
  apps/web/src/components/common/auction-card/card.tsx
  apps/web/src/components/ui/thumbnail.tsx
Labels: 🔨 Refactor

#454 [feat] updateAuctionStatus
  apps/web/app/api/auctions/route.ts
  apps/web/app/api/categories/route.ts
  apps/web/src/components/auction-detail/bid-form/form.tsx
  apps/web/src/components/auction-detail/container.tsx
  apps/web/src/components/auction-detail/countdown.tsx
  apps/web/src/components/auction-detail/item-description.tsx
  apps/web/src/components/auction-detail/item-summary.tsx
  apps/web/src/components/auction-detail/skeleton.tsx
  apps/web/src/components/chat/product-info-card.tsx
  apps/web/src/components/common/auction-card/card.tsx
  apps/web/src/components/layout/header/auction.tsx
  apps/web/src/hooks/common/useCountdown.ts
  apps/web/src/hooks/mutations/bids/index.ts
  apps/web/src/hooks/queries/auction/index.ts
  apps/web/src/hooks/queries/auction/keys.ts
  apps/web/src/lib/actions/auction.ts
  apps/web/src/lib/api/auction.ts
  apps/web/src/lib/api/client.ts
  apps/web/src/lib/types/auction-prisma.ts
  apps/web/src/lib/types/auction.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📝 Style, 💬 Comment
